spring:
  temporal:
    connection:
      target: ${TEMPORAL_ADDRESS:localhost:7233}
      enable-https: ${TEMPORAL_HTTPS:false}
    namespace: ${TEMPORAL_NAMESPACE:default}
    start-workers: true
    workers:
      - task-queue: ${BENCHMARKER_TASKQUEUE:default}
        capacity:
          max-concurrent-workflow-task-executors: ${BENCHMARKER_EXECUTORS:200}
          max-concurrent-activity-executors: 2
          max-concurrent-local-activity-executors: 2
          max-concurrent-workflow-task-pollers: ${BENCHMARKER_POLLERS:5}
          max-concurrent-activity-task-pollers: 2
        workflow-classes: 
          - "dev.loop.temporalio.benchmarker.workflowworker.workflow.BenchmarkerWorkflowImpl"
management.endpoints.web.exposure.include: health,info,prometheus
benchmarker:
  activity-task-queue: ${BENCHMARKER_ACTIVITY_TASKQUEUE:default}